name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env: # Global environment variables
  NODE_VERSION: '22.22.0'
  APP_NAME: 'cron-ticker-v2'

jobs:
  build: #Job build
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show variables
        run: |
          echo "Node Version: ${{ env.NODE_VERSION }}"
          echo "App Name: ${{ env.APP_NAME }}"
          echo "Build Directory: ${{ env.BUILD_DIR }}"

      - name: Build
        run: npm run build

        env:
          APP_VERSION: "3.0.0"